Azure KeyVault configuration implemented
srp-internships/MRA-Jobs pull request #122
Opened 2023-08-10 05:15 UTC by LastPeaksStorm

Azure KeyVault Secrets implemented to the project

2023-08-10 06:46 UTC, komdil requested changes

2023-08-10 06:46 UTC, komdil commented on Infrastructure.IntegrationTests/Infrastructure.IntegrationTests.csproj
> +    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.2" />
it should be only in Web.UI project

2023-08-10 06:46 UTC, komdil commented on MRA.Jobs.Infrastructure.Shared/MRA.Jobs.Infrastructure.Shared.csproj
> +  <ItemGroup>
it should be only in Web.UI project

2023-08-10 06:46 UTC, komdil commented on src/Application.Contracts/MRA.Jobs.Application.Contracts.csproj
> +    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.2" />
it should be only in Web.UI project

2023-08-10 06:46 UTC, komdil commented on src/Application/MRA.Jobs.Application.csproj
> +        <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.2" />
it should be only in Web.UI project

2023-08-10 06:46 UTC, komdil commented on src/Domain/MRA.Jobs.Domain.csproj
> +      <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.2" />
it should be only in Web.UI project

2023-08-10 06:46 UTC, komdil commented on src/Infrastructure/MRA.Jobs.Infrastructure.csproj
> +        <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.2" />
it should be only in Web.UI project

2023-08-10 06:46 UTC, komdil commented on src/MRA.Jobs.Client/MRA.Jobs.Client.csproj
> +    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.2" />
it should be only in Web.UI project

2023-08-10 06:46 UTC, komdil commented on src/WebUI/appsettings.json
> +  "KeyVaultName": "MRA-Key-Value",
It would be good if you can group this. For example, under AzureKeyVault

2023-08-10 06:46 UTC, komdil commented on tests/Application.IntegrationTests/Application.IntegrationTests.csproj
> +        <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.2" />
it should be only in Web.UI project

2023-08-10 06:46 UTC, komdil commented on tests/Application.UnitTests/Application.UnitTests.csproj
> +        <PackageReference Include="Azure.Identity" Version="1.9.0" />
it should be only in Web.UI project

2023-08-10 06:46 UTC, komdil commented on tests/Domain.UnitTests/Domain.UnitTests.csproj
> +        <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.2" />
it should be only in Web.UI project

2023-08-12 11:47 UTC, komdil approved these changes

2023-08-15 09:11 UTC, Muhammadislom99 approved these changes

2023-08-15 09:32 UTC, komdil approved these changes

2023-08-15 09:33 UTC, merged