Auth
srp-internships/MRA-Jobs pull request #123
Opened 2023-08-10 05:37 UTC by Firuz2006

2023-08-10 06:21 UTC, komdil requested changes

2023-08-10 06:21 UTC, komdil commented on MRA.Identity/src/MRA.Identity.Infrastructure/DependencyInitializer.cs
> +                // options.Password.RequiredLength = 8;
remove commented lines if no need

2023-08-10 06:21 UTC, komdil commented on MRA.Identity/src/MRA.Identity.Infrastructure/Persistence/ApplicationDbContext.cs
> +    {
remove it

2023-08-10 09:21 UTC, Firuz2006 commented on MRA.Identity/src/MRA.Identity.Application/Services/JwtTokenService.cs
> +    internal static string SecretKey="123";
![изображение](https://github.com/srp-internships/MRA-Jobs/assets/88187420/713864a9-92fc-43fc-8b89-bb46f2c68bc0)

2023-08-10 09:21 UTC, Firuz2006 commented on MRA.Identity/src/MRA.Identity.Application/Services/JwtTokenService.cs
> +    internal static string SecretKey="123";
is it wrong?

2023-08-11 09:38 UTC, komdil approved these changes

2023-08-11 09:42 UTC, Muhammadislom99 approved these changes

2023-08-11 09:42 UTC, merged