Emile service
srp-internships/MRA-Jobs pull request #133
Opened 2023-08-15 08:46 UTC by Ubaydulloev1104

2023-08-16 09:52 UTC, komdil requested changes

2023-08-16 09:52 UTC, komdil commented on MRA.Identity/src/MRA.Identity.Application/Services/EmailService.cs
> +public class EmailService : IEmailService
Should it be in Infrastructure Layer?

2023-08-17 17:19 UTC, Muhammadislom99 approved these changes

2023-08-17 17:19 UTC, Muhammadislom99 approved these changes

2023-08-18 06:00 UTC, komdil approved these changes

2023-08-18 06:02 UTC, merged