finishAuthTests
srp-internships/MRA-Jobs pull request #165
Opened 2023-08-23 11:50 UTC by Avazbek22

2023-08-23 12:01 UTC, komdil requested changes

2023-08-23 12:01 UTC, komdil commented on tests/MRA.Jobs.Identity/Application.IntegrationTests/RegistrationTest.cs
> +        var content = new StringContent(JsonConvert.SerializeObject(request), Encoding.UTF8, "application/json");
use PostAsJsonAsync

2023-08-23 12:01 UTC, komdil commented on tests/MRA.Jobs.Identity/Application.IntegrationTests/RegistrationTest.cs
> +        var result = _context.Users.Count();
This should be under assert comment

2023-08-23 12:01 UTC, komdil commented on tests/MRA.Jobs.Identity/Application.IntegrationTests/RegistrationTest.cs
> +        var response = await _client.PostAsync("api/Auth/register", content);
use PostAsJsonAsync

2023-08-25 10:03 UTC, komdil submitted a review, later dismissed

2023-08-25 10:47 UTC, Firuz2006 requested changes

2023-08-25 10:47 UTC, Firuz2006 commented on tests/MRA.Jobs.Identity/Application.IntegrationTests/RegistrationTest.cs
> +
I recommend removing this test

2023-08-25 10:47 UTC, Firuz2006 commented on tests/MRA.Jobs.Identity/Application.IntegrationTests/RegistrationTest.cs
> +       // Assert.That(_context.Users.Count(), Is.EqualTo(1));
enable database checking

2023-08-25 11:28 UTC, Firuz2006 approved these changes

2023-08-25 11:31 UTC, komdil approved these changes

2023-08-25 11:32 UTC, merged