Users roles
srp-internships/MRA-Jobs pull request #184
Opened 2023-08-31 06:47 UTC by LayloMirdadoeva

Must be drop database and update database

2023-08-31 07:33 UTC, komdil requested changes

2023-08-31 07:33 UTC, komdil commented on src/MRA.Jobs.Identity/.idea/.idea.MRA.Identity/.idea/.gitignore
These files should be ignored

2023-08-31 07:33 UTC, komdil commented on src/MRA.Jobs.Identity/MRA.Identity.Api/Controllers/UserRolesController.cs
> +        var query = new GetUserRolesQuery { Role = role, UserName = userName };
Put GetUserRolesQuery as a parameter

2023-08-31 07:33 UTC, komdil commented on src/MRA.Jobs.Identity/MRA.Identity.Application/ApplicationResponseBuilder.cs
> +    internal ApplicationResponse<List<UserRolesResponse>> SetResponse(List<Task<UserRolesResponse>> list)
I think you can remove it

2023-08-31 07:33 UTC, komdil commented on src/MRA.Jobs.Identity/MRA.Identity.Application/Features/UserRoles/Commands/CreateUserRoleCommandHandler.cs
> +           // return new ApplicationResponseBuilder<Guid>().SetErrorMessage(result.Errors.First().Description).Success(false).Build();
remove

2023-08-31 08:07 UTC, LayloMirdadoeva commented on src/MRA.Jobs.Identity/MRA.Identity.Api/Controllers/UserRolesController.cs
> +        var query = new GetUserRolesQuery { Role = role, UserName = userName };
![image](https://github.com/srp-internships/MRA-Jobs/assets/120080211/192f1e91-51db-4d29-b8e6-85bd970805d7)
агар хаминхел кунем , ошибка баромадос

2023-08-31 08:13 UTC, LayloMirdadoeva commented on src/MRA.Jobs.Identity/MRA.Identity.Application/ApplicationResponseBuilder.cs
> +    internal ApplicationResponse<List<UserRolesResponse>> SetResponse(List<Task<UserRolesResponse>> list)
![image](https://github.com/srp-internships/MRA-Jobs/assets/120080211/b007221a-ad47-4d26-9c77-62df10690e33)
Агар удалить кунем ин метод кор намекунад

2023-08-31 08:15 UTC, LayloMirdadoeva commented on src/MRA.Jobs.Identity/.idea/.idea.MRA.Identity/.idea/.gitignore
Удалить кардем, инсфа факат VisualStudio кати кор мекунем ба чои Rider, gitignor ба добавить нашудос

2023-08-31 08:19 UTC, LayloMirdadoeva commented on src/MRA.Jobs.Identity/MRA.Identity.Application/Features/UserRoles/Commands/CreateUserRoleCommandHandler.cs
> +           // return new ApplicationResponseBuilder<Guid>().SetErrorMessage(result.Errors.First().Description).Success(false).Build();
removed

2023-08-31 08:21 UTC, Muhammadislom99 approved these changes

2023-09-01 03:27 UTC, komdil approved these changes

2023-09-01 03:28 UTC, komdil commented
@LayloMirdadoeva It would be good to add some tests

2023-09-01 03:28 UTC, merged