Phone verification
srp-internships/MRA-Jobs pull request #205
Opened 2023-09-07 05:47 UTC by adheeeem

2023-09-13 11:01 UTC, komdil requested changes

2023-09-13 11:01 UTC, komdil commented on src/MRA.Jobs.Identity/MRA.Identity.Application/Features/Users/Query/SmsVerificationCodeCheckQueryHandler.cs
> +            await _userManager.UpdateAsync(user);
Make sure that it was successfully saved

2023-09-14 09:05 UTC, Firuz2006 submitted a review, later dismissed

2023-09-14 10:50 UTC, komdil approved these changes

2023-09-14 10:51 UTC, Muhammadislom99 approved these changes

2023-09-14 10:51 UTC, merged