trainings auth
srp-internships/MRA-Jobs pull request #213
Opened 2023-09-12 14:09 UTC by Firuz2006

2023-09-12 14:59 UTC, komdil requested changes

2023-09-12 14:59 UTC, komdil commented on src/MRA.Jobs.Api/WebUI/Controllers/ApplicationsController.cs
> +    [AllowAnonymous]
[Authorize(ApplicationPolicies.Reviewer)]
Only reviewer can see applications

2023-09-12 14:59 UTC, komdil commented on src/MRA.Jobs.Api/WebUI/Controllers/ApplicationsController.cs
> +    [AllowAnonymous]
reviewer only

2023-09-12 14:59 UTC, komdil commented on src/MRA.Jobs.Api/WebUI/Controllers/ApplicationsController.cs
> +    [Authorize]
This one is correct

2023-09-12 14:59 UTC, komdil commented on src/MRA.Jobs.Api/WebUI/Controllers/ApplicationsController.cs
> +    [AllowAnonymous]
reviewer only

2023-09-12 14:59 UTC, komdil commented on src/MRA.Jobs.Api/WebUI/Controllers/InternshipsController.cs
>      {
remove this route

2023-09-12 15:55 UTC, komdil approved these changes

2023-09-13 02:13 UTC, adheeeem approved these changes

2023-09-13 02:13 UTC, merged