Response handling on client and server
srp-internships/MRA-Jobs pull request #280
Opened 2023-10-12 09:34 UTC by Ubaydulloev1104

2023-10-16 06:53 UTC, komdil requested changes

2023-10-16 06:53 UTC, komdil commented on src/MRA.Jobs.Api/Application.Contracts/MRA.Jobs.Application.Contracts.csproj
> +        <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
This is wrong, it should not be dependent on asp.net core

2023-10-16 06:53 UTC, komdil commented on src/MRA.Jobs.Identity/MRA.Identity.Api/Controllers/UserRolesController.cs
> +        .Send(new GetUserRolesQuery
Just put this on parameter, Don't create it

2023-10-17 03:18 UTC, komdil approved these changes

2023-10-17 03:21 UTC, adheeeem approved these changes

2023-10-17 03:23 UTC, merged